apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: pod-reader
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs: [create,delete,deletecollection,get,list,patch,update,watch]
